language: erlang

env:
  - LUA=""
  - LUA="luajit"

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted
  - sudo luarocks install luasocket
  - sudo luarocks install lua-ev
  - sudo luarocks install lua-cjson
  - sudo luarocks install lpack

script: "busted spec"

